package virtualzoo.ui;

/*
 *  Java Programming Step-by-Step
 *  Copyright 2012, Ability First Limited
 *
 *  This source code is provided to accompany the book and is provided AS-IS without warranty of any kind.
 *  It is intended for educational and illustrative purposes only, and may not be re-published
 *  without the express written permission of the publisher.
 */

import virtualzoo.core.*;
import com.example.util.*;
import java.util.*;
import javax.swing.*;

/**
 *
 * @author Tony
 */
public class AnimalEditor extends javax.swing.JPanel {

    private Animal animal;

    /** Creates new form AnimalEditor */
    public AnimalEditor() {
        initComponents();
        clearAnimal();
    }

    void clearAnimal() {
        animal = null;
        animalTypeCombo.setSelectedIndex(0);
        penCombo.setSelectedIndex(0);
        nameField.setText("");
        maleOption.setSelected(false);
        femaleOption.setSelected(false);
        ageSpinner.setValue(0);
        modeLabel.setText("Add New Animal");
        messageLabel.setText("");
    }

    void setAnimal(Animal animal) {
        this.animal = animal;
        animalTypeCombo.setSelectedItem(animal.getType());
        penCombo.setSelectedItem(animal.getPen());
        nameField.setText(animal.getName());
        if (animal.isMale()) {
            maleOption.setSelected(true);
        } else {
            femaleOption.setSelected(true);
        }
        ageSpinner.setValue(animal.getAge());
        modeLabel.setText("Change Animal Details");
        messageLabel.setText("");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderButtonGroup = new javax.swing.ButtonGroup();
        modeLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        animalTypeCombo = new JComboBox(Animal.Type.values());
        ZooAdministrator admin = ZooAdministrator.getInstance();
        Collection<Pen> pens = admin.getPens();
        Pen[] pensArray = pens.toArray(new Pen[pens.size()]);
        penCombo = new JComboBox(pensArray);
        nameField = new javax.swing.JTextField();
        maleOption = new javax.swing.JRadioButton();
        femaleOption = new javax.swing.JRadioButton();
        SpinnerNumberModel ageSpinnerModel = new SpinnerNumberModel(0, 0, 50, 1);
        ageSpinner = new JSpinner(ageSpinnerModel);
        saveButton = new javax.swing.JButton();
        messageLabel = new javax.swing.JLabel();

        modeLabel.setFont(new java.awt.Font("Tahoma", 1, 11));
        modeLabel.setText("Mode will go here");

        jLabel1.setText("Animal type:");

        jLabel2.setText("Pen:");

        jLabel3.setText("Name:");

        jLabel4.setText("Gender:");

        jLabel5.setText("Age:");

        genderButtonGroup.add(maleOption);
        maleOption.setSelected(true);
        maleOption.setText("Male");

        genderButtonGroup.add(femaleOption);
        femaleOption.setText("Female");

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        messageLabel.setFont(new java.awt.Font("Tahoma", 0, 18));
        messageLabel.setForeground(new java.awt.Color(51, 102, 255));
        messageLabel.setText("Message will go here");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(modeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(messageLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                            .addComponent(penCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(animalTypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(ageSpinner, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(maleOption, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(femaleOption))
                            .addComponent(saveButton))))
                .addGap(65, 65, 65))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(modeLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(animalTypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(penCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(maleOption)
                    .addComponent(femaleOption))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(ageSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(saveButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(messageLabel)
                .addContainerGap(22, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        ZooAdministrator admin = ZooAdministrator.getInstance();

        try {
            // Prepare selected data
            Animal.Type selectedAnimalType =
                    (Animal.Type) animalTypeCombo.getSelectedItem();
            Pen selectedPen = (Pen) penCombo.getSelectedItem();
            Gender selectedAnimalGender = null;
            if (maleOption.isSelected()) {
                selectedAnimalGender = Gender.MALE;
            } else {
                selectedAnimalGender = Gender.FEMALE;
            }
            int selectedAge = (Integer) ageSpinner.getValue();

            if (animal == null) {
                // Adding a new animal
                admin.createAnimal(selectedAnimalType,
                        selectedPen,
                        nameField.getText(),
                        selectedAnimalGender,
                        selectedAge);
                messageLabel.setText("New animal added");
                clearAnimal();

            } else {
                // Changing an existing animal
                admin.changeAnimal(animal,
                        selectedPen,
                        nameField.getText(),
                        selectedAnimalGender,
                        selectedAge);
                messageLabel.setText("Animal details changed");
            }
        } catch (ValidationException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_saveButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner ageSpinner;
    private javax.swing.JComboBox animalTypeCombo;
    private javax.swing.JRadioButton femaleOption;
    private javax.swing.ButtonGroup genderButtonGroup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton maleOption;
    private javax.swing.JLabel messageLabel;
    private javax.swing.JLabel modeLabel;
    private javax.swing.JTextField nameField;
    private javax.swing.JComboBox penCombo;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}
