package virtualzoo.ui;

/*
 *  Java Programming Step-by-Step
 *  Copyright 2012, Ability First Limited
 *
 *  This source code is provided to accompany the book and is provided AS-IS without warranty of any kind.
 *  It is intended for educational and illustrative purposes only, and may not be re-published
 *  without the express written permission of the publisher.
 */

import virtualzoo.core.*;

import javax.swing.*;
import javax.swing.event.*;
import javax.swing.tree.*;

/**
 *
 * @author Tony
 */
public class AnimalPanel extends javax.swing.JPanel implements TreeSelectionListener {

    private ZooAdministrator admin;

    /** Creates new form AnimalPanel */
    public AnimalPanel() {
        initComponents();
        admin = ZooAdministrator.getInstance();
        admin.addAnimalListener(animalTree);
        animalTree.addTreeSelectionListener(this);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        addButton = new javax.swing.JButton();
        removeButton = new javax.swing.JButton();
        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        animalTree = new virtualzoo.ui.AnimalTree();
        animalEditor = new virtualzoo.ui.AnimalEditor();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        jPanel1.add(addButton);

        removeButton.setText("Remove");
        removeButton.setEnabled(false);
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });
        jPanel1.add(removeButton);

        add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jScrollPane1.setViewportView(animalTree);

        jSplitPane1.setLeftComponent(jScrollPane1);
        jSplitPane1.setRightComponent(animalEditor);

        add(jSplitPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
        DefaultMutableTreeNode selectedNode = (DefaultMutableTreeNode) animalTree.getLastSelectedPathComponent();
        if (selectedNode != null) {
            Object selectedObject = selectedNode.getUserObject();
            if (selectedObject instanceof Animal) {
                Animal selectedAnimal = (Animal) selectedObject;
                int response = JOptionPane.showConfirmDialog(null,
                        "Do you really want to remove "
                        + selectedAnimal.getName() + "?",
                        "Confirm Remove", JOptionPane.YES_NO_OPTION);
                if (response == JOptionPane.YES_OPTION) {
                    admin.removeAnimal(selectedAnimal);
                    animalEditor.clearAnimal();
                }
            }
        }
    }//GEN-LAST:event_removeButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        animalEditor.clearAnimal();
        animalTree.getSelectionModel().clearSelection();
    }//GEN-LAST:event_addButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private virtualzoo.ui.AnimalEditor animalEditor;
    private virtualzoo.ui.AnimalTree animalTree;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton removeButton;
    // End of variables declaration//GEN-END:variables

    @Override
    public void valueChanged(TreeSelectionEvent e) {
        // A node has been selected from AnimalTree
        DefaultMutableTreeNode selectedNode = (DefaultMutableTreeNode) animalTree.getLastSelectedPathComponent();
        removeButton.setEnabled(false);
        if (selectedNode != null) {
            Object selectedObject = selectedNode.getUserObject();
            if (selectedObject instanceof Animal) {
                Animal selectedAnimal = (Animal) selectedObject;
                animalEditor.setAnimal(selectedAnimal);
                removeButton.setEnabled(true);
            }
        }
    }
}
