package virtualzoo.ui;

/*
 *  Java Programming Step-by-Step
 *  Copyright 2012, Ability First Limited
 *
 *  This source code is provided to accompany the book and is provided AS-IS without warranty of any kind.
 *  It is intended for educational and illustrative purposes only, and may not be re-published
 *  without the express written permission of the publisher.
 */

import javax.swing.JOptionPane;
import virtualzoo.core.*;
import javax.swing.event.*;

/**
 *
 * @author Tony
 */
public class ZooKeeperPanel extends javax.swing.JPanel implements ListSelectionListener {

    private ZooAdministrator admin;

    /** Creates new form ZooKeeperPanel */
    public ZooKeeperPanel() {
        initComponents();
        admin = ZooAdministrator.getInstance();
        admin.addZooKeeperListener(zooKeeperList);
        zooKeeperList.addListSelectionListener(this);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        addButton = new javax.swing.JButton();
        removeButton = new javax.swing.JButton();
        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        zooKeeperList = new virtualzoo.ui.ZooKeeperList();
        zooKeeperEditor = new virtualzoo.ui.ZooKeeperEditor();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        jPanel1.add(addButton);

        removeButton.setText("Remove");
        removeButton.setEnabled(false);
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });
        jPanel1.add(removeButton);

        add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jScrollPane1.setViewportView(zooKeeperList);

        jSplitPane1.setLeftComponent(jScrollPane1);
        jSplitPane1.setRightComponent(zooKeeperEditor);

        add(jSplitPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
        ZooKeeper zooKeeper = (ZooKeeper) zooKeeperList.getSelectedValue();
        int response = JOptionPane.showConfirmDialog(null,
                "Do you really want to remove " + zooKeeper.getName() + "?",
                "Confirm Remove", JOptionPane.YES_NO_OPTION);
        if (response == JOptionPane.YES_OPTION) {
            admin.removeZooKeeper(zooKeeper);
            zooKeeperEditor.clearZooKeeper();
        }
    }//GEN-LAST:event_removeButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        zooKeeperList.deselectListItems();
        zooKeeperEditor.clearZooKeeper();
    }//GEN-LAST:event_addButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton removeButton;
    private virtualzoo.ui.ZooKeeperEditor zooKeeperEditor;
    private virtualzoo.ui.ZooKeeperList zooKeeperList;
    // End of variables declaration//GEN-END:variables

    @Override
    public void valueChanged(ListSelectionEvent e) {
        // A zoo keeper has been selected from ZooKeeperList
        Object selected = zooKeeperList.getSelectedValue();
        if (selected != null) {
            ZooKeeper zooKeeper = (ZooKeeper) selected;
            zooKeeperEditor.setZooKeeper(zooKeeper);
            removeButton.setEnabled(true);
        } else {
            // Nothing selected
            removeButton.setEnabled(false);
        }
    }
}
